# Generated by Django 5.2.16 on 2026-09-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dapp', '0003_alter_cartitem_id_alter_item_id_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=100),
        ),
    ]
